name: Deploy docker images to Docker Hub

on:
  workflow_dispatch:

  push:
    branches:
      - stable

jobs:
  push_image:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - experimental: true
            tag: latest
            haproxy_image: eeacms/haproxy:latest
          - experimental: false
            tag: "1.18"
            haproxy_image: eeacms/haproxy:1.8-1.7

    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            HAPROXY_IMAGE=${{ matrix.haproxy_image }}
          context: .
          push: true
          tags: |
            tenshiamd/haproxy:${{ matrix.tag }}
            
